import ACSquareFamily

/-!
# A uniform descent for the diagonal square family

The 71-step recurrence decreases the integer parameter by one. Its discovery
input was the retained G(3,3,+1) path, but the proof below checks identities in
the free group for arbitrary integer s. Induction supplies complete solutions.

Generated by research/square-general/generate_diagonal_lean.py. Each equality
is independently elaborated by Lean; no computed Python equality is assumed.
-/

namespace AC.MillerSchupp.SquareFamily.Diagonal

open AC.Certificate

def diagonal (s : ℤ) : Relators 2 := pair (square s (s + 1)) (relation s s)

def generalSquare (p s : ℤ) : Relators 2 := pair (square s (s + 1)) (relation p s)

def normalForm (p s : ℤ) : Relators 2 :=
  pair (y ^ (-p) * x⁻¹ * y ^ p * x⁻¹ * y ^ s * x)
    (x * y ^ (-p) * x⁻¹ * x⁻¹ * y ^ p * x * y⁻¹)

private theorem conj0 (r q g z : Word 2)
    (he : g * r * g⁻¹ = z) : Steps (pair r q) 1 (pair z q) := by
  simpa only [pair_zero, pair_one, he, pair_update_zero] using
    Steps.single (Step.conj (pair r q) 0 g)

private theorem conj1 (r q g z : Word 2)
    (he : g * q * g⁻¹ = z) : Steps (pair r q) 1 (pair r z) := by
  simpa only [pair_zero, pair_one, he, pair_update_one] using
    Steps.single (Step.conj (pair r q) 1 g)

private theorem inv0 (r q z : Word 2)
    (he : r⁻¹ = z) : Steps (pair r q) 1 (pair z q) := by
  simpa only [pair_zero, pair_one, he, pair_update_zero] using
    Steps.single (Step.inv (pair r q) 0)

private theorem inv1 (r q z : Word 2)
    (he : q⁻¹ = z) : Steps (pair r q) 1 (pair r z) := by
  simpa only [pair_zero, pair_one, he, pair_update_one] using
    Steps.single (Step.inv (pair r q) 1)

private theorem mul0 (r q z : Word 2)
    (he : r * q = z) : Steps (pair r q) 1 (pair z q) := by
  simpa only [pair_zero, pair_one, he, pair_update_zero] using
    Steps.single (Step.mulRight (pair r q) 0 1 (by decide))

private theorem mul1 (r q z : Word 2)
    (he : q * r = z) : Steps (pair r q) 1 (pair r z) := by
  simpa only [pair_zero, pair_one, he, pair_update_one] using
    Steps.single (Step.mulRight (pair r q) 1 0 (by decide))

private theorem neg0 (r q z : Word 2)
    (he : r * q⁻¹ = z) : Steps (pair r q) 3 (pair z q) := by
  simpa only [pair_zero, pair_one, he, pair_update_zero] using
    Steps.mulInvRight (pair r q) 0 1 (by decide)

private theorem neg1 (r q z : Word 2)
    (he : q * r⁻¹ = z) : Steps (pair r q) 3 (pair r z) := by
  simpa only [pair_zero, pair_one, he, pair_update_one] using
    Steps.mulInvRight (pair r q) 1 0 (by decide)

/-- A uniform normal form for the entire positive-sign square family. -/
theorem general_normal_form (p s : ℤ) :
    Steps (generalSquare p s) 18 (normalForm p s) := by
  have hi : generalSquare p s = pair (x * x * y ^ (-2 * s - 1 : ℤ)) (x * y ^ (p : ℤ) * x * y ^ (-s : ℤ) * x⁻¹ * y ^ (-p : ℤ)) := by
    ext i
    fin_cases i <;> simp [generalSquare, square, relation, pair, pow_two]; group
  have h1 : Steps (pair (x * x * y ^ (-2 * s - 1 : ℤ)) (x * y ^ (p : ℤ) * x * y ^ (-s : ℤ) * x⁻¹ * y ^ (-p : ℤ))) 1
      (pair (y ^ (-2 * s - 1 : ℤ) * x * x) (x * y ^ (p : ℤ) * x * y ^ (-s : ℤ) * x⁻¹ * y ^ (-p : ℤ))) :=
    conj0 _ _ (x⁻¹ * x⁻¹) _ (by group; simp only [zpow_ofNat, pow_two, mul_assoc])
  have h2 : Steps (pair (y ^ (-2 * s - 1 : ℤ) * x * x) (x * y ^ (p : ℤ) * x * y ^ (-s : ℤ) * x⁻¹ * y ^ (-p : ℤ))) 1
      (pair (y ^ (-2 * s - 1 : ℤ) * x * x) (y ^ (-s : ℤ) * x⁻¹ * y ^ (-p : ℤ) * x * y ^ (p : ℤ) * x)) :=
    conj1 _ _ (x⁻¹ * y ^ (-p : ℤ) * x⁻¹) _ (by group)
  have h3 : Steps (pair (y ^ (-2 * s - 1 : ℤ) * x * x) (y ^ (-s : ℤ) * x⁻¹ * y ^ (-p : ℤ) * x * y ^ (p : ℤ) * x)) 3
      (pair (y ^ (-2 * s - 1 : ℤ) * x * y ^ (-p : ℤ) * x⁻¹ * y ^ (p : ℤ) * x * y ^ (s : ℤ)) (y ^ (-s : ℤ) * x⁻¹ * y ^ (-p : ℤ) * x * y ^ (p : ℤ) * x)) :=
    neg0 _ _ _ (by group)
  have h4 : Steps (pair (y ^ (-2 * s - 1 : ℤ) * x * y ^ (-p : ℤ) * x⁻¹ * y ^ (p : ℤ) * x * y ^ (s : ℤ)) (y ^ (-s : ℤ) * x⁻¹ * y ^ (-p : ℤ) * x * y ^ (p : ℤ) * x)) 1
      (pair (y ^ (-s - 1 : ℤ) * x * y ^ (-p : ℤ) * x⁻¹ * y ^ (p : ℤ) * x) (y ^ (-s : ℤ) * x⁻¹ * y ^ (-p : ℤ) * x * y ^ (p : ℤ) * x)) :=
    conj0 _ _ (y ^ (s : ℤ)) _ (by group)
  have h5 : Steps (pair (y ^ (-s - 1 : ℤ) * x * y ^ (-p : ℤ) * x⁻¹ * y ^ (p : ℤ) * x) (y ^ (-s : ℤ) * x⁻¹ * y ^ (-p : ℤ) * x * y ^ (p : ℤ) * x)) 3
      (pair (y ^ (-s - 1 : ℤ) * x * y ^ (-p : ℤ) * x⁻¹ * y ^ (p : ℤ) * x) (y ^ (-s : ℤ) * x⁻¹ * y ^ (-p : ℤ) * x * x * y ^ (p : ℤ) * x⁻¹ * y ^ (s + 1 : ℤ))) :=
    neg1 _ _ _ (by group)
  have h6 : Steps (pair (y ^ (-s - 1 : ℤ) * x * y ^ (-p : ℤ) * x⁻¹ * y ^ (p : ℤ) * x) (y ^ (-s : ℤ) * x⁻¹ * y ^ (-p : ℤ) * x * x * y ^ (p : ℤ) * x⁻¹ * y ^ (s + 1 : ℤ))) 1
      (pair (y ^ (-s - 1 : ℤ) * x * y ^ (-p : ℤ) * x⁻¹ * y ^ (p : ℤ) * x) (x⁻¹ * y ^ (-p : ℤ) * x * x * y ^ (p : ℤ) * x⁻¹ * y)) :=
    conj1 _ _ (y ^ (s : ℤ)) _ (by group)
  have h7 : Steps (pair (y ^ (-s - 1 : ℤ) * x * y ^ (-p : ℤ) * x⁻¹ * y ^ (p : ℤ) * x) (x⁻¹ * y ^ (-p : ℤ) * x * x * y ^ (p : ℤ) * x⁻¹ * y)) 1
      (pair (y ^ (-s - 1 : ℤ) * x * y ^ (-p : ℤ) * x⁻¹ * y ^ (p : ℤ) * x) (y⁻¹ * x * y ^ (-p : ℤ) * x⁻¹ * x⁻¹ * y ^ (p : ℤ) * x)) :=
    inv1 _ _ _ (by group)
  have h8 : Steps (pair (y ^ (-s - 1 : ℤ) * x * y ^ (-p : ℤ) * x⁻¹ * y ^ (p : ℤ) * x) (y⁻¹ * x * y ^ (-p : ℤ) * x⁻¹ * x⁻¹ * y ^ (p : ℤ) * x)) 1
      (pair (y ^ (-s : ℤ) * x * y ^ (-p : ℤ) * x⁻¹ * y ^ (p : ℤ) * x * y⁻¹) (y⁻¹ * x * y ^ (-p : ℤ) * x⁻¹ * x⁻¹ * y ^ (p : ℤ) * x)) :=
    conj0 _ _ (y) _ (by group)
  have h9 : Steps (pair (y ^ (-s : ℤ) * x * y ^ (-p : ℤ) * x⁻¹ * y ^ (p : ℤ) * x * y⁻¹) (y⁻¹ * x * y ^ (-p : ℤ) * x⁻¹ * x⁻¹ * y ^ (p : ℤ) * x)) 1
      (pair (y ^ (-s : ℤ) * x * y ^ (-p : ℤ) * x⁻¹ * y ^ (p : ℤ) * x * y⁻¹) (x * y ^ (-p : ℤ) * x⁻¹ * x⁻¹ * y ^ (p : ℤ) * x * y⁻¹)) :=
    conj1 _ _ (y) _ (by group)
  have h10 : Steps (pair (y ^ (-s : ℤ) * x * y ^ (-p : ℤ) * x⁻¹ * y ^ (p : ℤ) * x * y⁻¹) (x * y ^ (-p : ℤ) * x⁻¹ * x⁻¹ * y ^ (p : ℤ) * x * y⁻¹)) 3
      (pair (y ^ (-s : ℤ) * x * y ^ (-p : ℤ) * x * y ^ (p : ℤ) * x⁻¹) (x * y ^ (-p : ℤ) * x⁻¹ * x⁻¹ * y ^ (p : ℤ) * x * y⁻¹)) :=
    neg0 _ _ _ (by group)
  have h11 : Steps (pair (y ^ (-s : ℤ) * x * y ^ (-p : ℤ) * x * y ^ (p : ℤ) * x⁻¹) (x * y ^ (-p : ℤ) * x⁻¹ * x⁻¹ * y ^ (p : ℤ) * x * y⁻¹)) 1
      (pair (x * y ^ (-p : ℤ) * x⁻¹ * y ^ (p : ℤ) * x⁻¹ * y ^ (s : ℤ)) (x * y ^ (-p : ℤ) * x⁻¹ * x⁻¹ * y ^ (p : ℤ) * x * y⁻¹)) :=
    inv0 _ _ _ (by group)
  have h12 : Steps (pair (x * y ^ (-p : ℤ) * x⁻¹ * y ^ (p : ℤ) * x⁻¹ * y ^ (s : ℤ)) (x * y ^ (-p : ℤ) * x⁻¹ * x⁻¹ * y ^ (p : ℤ) * x * y⁻¹)) 1
      (pair (y ^ (-p : ℤ) * x⁻¹ * y ^ (p : ℤ) * x⁻¹ * y ^ (s : ℤ) * x) (x * y ^ (-p : ℤ) * x⁻¹ * x⁻¹ * y ^ (p : ℤ) * x * y⁻¹)) :=
    conj0 _ _ (x⁻¹) _ (by group)
  have he : normalForm p s = pair (y ^ (-p : ℤ) * x⁻¹ * y ^ (p : ℤ) * x⁻¹ * y ^ (s : ℤ) * x) (x * y ^ (-p : ℤ) * x⁻¹ * x⁻¹ * y ^ (p : ℤ) * x * y⁻¹) := by
    ext i
    fin_cases i <;> simp [normalForm, pair]
  rw [hi, he]
  exact (((((((((((h1.trans h2).trans h3).trans h4).trans h5).trans h6).trans h7).trans h8).trans h9).trans h10).trans h11).trans h12)

/-- An exact uniform recurrence made of ordinary moves only. -/
theorem descent (s : ℤ) : Steps (diagonal s) 71 (diagonal (s - 1)) := by
  have hi : diagonal s = pair (x * x * y ^ (-2 * s - 1 : ℤ)) (x * y ^ (s : ℤ) * x * y ^ (-s : ℤ) * x⁻¹ * y ^ (-s : ℤ)) := by
    ext i
    fin_cases i <;> simp [diagonal, square, relation, pair, pow_two]; group
  have h1 : Steps (pair (x * x * y ^ (-2 * s - 1 : ℤ)) (x * y ^ (s : ℤ) * x * y ^ (-s : ℤ) * x⁻¹ * y ^ (-s : ℤ))) 1
      (pair (y ^ (-2 * s - 1 : ℤ) * x * x) (x * y ^ (s : ℤ) * x * y ^ (-s : ℤ) * x⁻¹ * y ^ (-s : ℤ))) :=
    conj0 _ _ (x⁻¹ * x⁻¹) _ (by group; simp only [zpow_ofNat, pow_two, mul_assoc])
  have h2 : Steps (pair (y ^ (-2 * s - 1 : ℤ) * x * x) (x * y ^ (s : ℤ) * x * y ^ (-s : ℤ) * x⁻¹ * y ^ (-s : ℤ))) 1
      (pair (y ^ (-2 * s - 1 : ℤ) * x * x) (y ^ (-s : ℤ) * x⁻¹ * y ^ (-s : ℤ) * x * y ^ (s : ℤ) * x)) :=
    conj1 _ _ (x⁻¹ * y ^ (-s : ℤ) * x⁻¹) _ (by group)
  have h3 : Steps (pair (y ^ (-2 * s - 1 : ℤ) * x * x) (y ^ (-s : ℤ) * x⁻¹ * y ^ (-s : ℤ) * x * y ^ (s : ℤ) * x)) 3
      (pair (y ^ (-2 * s - 1 : ℤ) * x * y ^ (-s : ℤ) * x⁻¹ * y ^ (s : ℤ) * x * y ^ (s : ℤ)) (y ^ (-s : ℤ) * x⁻¹ * y ^ (-s : ℤ) * x * y ^ (s : ℤ) * x)) :=
    neg0 _ _ _ (by group)
  have h4 : Steps (pair (y ^ (-2 * s - 1 : ℤ) * x * y ^ (-s : ℤ) * x⁻¹ * y ^ (s : ℤ) * x * y ^ (s : ℤ)) (y ^ (-s : ℤ) * x⁻¹ * y ^ (-s : ℤ) * x * y ^ (s : ℤ) * x)) 1
      (pair (y ^ (-s - 1 : ℤ) * x * y ^ (-s : ℤ) * x⁻¹ * y ^ (s : ℤ) * x) (y ^ (-s : ℤ) * x⁻¹ * y ^ (-s : ℤ) * x * y ^ (s : ℤ) * x)) :=
    conj0 _ _ (y ^ (s : ℤ)) _ (by group)
  have h5 : Steps (pair (y ^ (-s - 1 : ℤ) * x * y ^ (-s : ℤ) * x⁻¹ * y ^ (s : ℤ) * x) (y ^ (-s : ℤ) * x⁻¹ * y ^ (-s : ℤ) * x * y ^ (s : ℤ) * x)) 3
      (pair (y ^ (-s - 1 : ℤ) * x * y ^ (-s : ℤ) * x⁻¹ * y ^ (s : ℤ) * x) (y ^ (-s : ℤ) * x⁻¹ * y ^ (-s : ℤ) * x * x * y ^ (s : ℤ) * x⁻¹ * y ^ (s + 1 : ℤ))) :=
    neg1 _ _ _ (by group)
  have h6 : Steps (pair (y ^ (-s - 1 : ℤ) * x * y ^ (-s : ℤ) * x⁻¹ * y ^ (s : ℤ) * x) (y ^ (-s : ℤ) * x⁻¹ * y ^ (-s : ℤ) * x * x * y ^ (s : ℤ) * x⁻¹ * y ^ (s + 1 : ℤ))) 1
      (pair (y ^ (-s - 1 : ℤ) * x * y ^ (-s : ℤ) * x⁻¹ * y ^ (s : ℤ) * x) (x⁻¹ * y ^ (-s : ℤ) * x * x * y ^ (s : ℤ) * x⁻¹ * y)) :=
    conj1 _ _ (y ^ (s : ℤ)) _ (by group)
  have h7 : Steps (pair (y ^ (-s - 1 : ℤ) * x * y ^ (-s : ℤ) * x⁻¹ * y ^ (s : ℤ) * x) (x⁻¹ * y ^ (-s : ℤ) * x * x * y ^ (s : ℤ) * x⁻¹ * y)) 1
      (pair (y ^ (-s - 1 : ℤ) * x * y ^ (-s : ℤ) * x⁻¹ * y ^ (s : ℤ) * x) (y⁻¹ * x * y ^ (-s : ℤ) * x⁻¹ * x⁻¹ * y ^ (s : ℤ) * x)) :=
    inv1 _ _ _ (by group)
  have h8 : Steps (pair (y ^ (-s - 1 : ℤ) * x * y ^ (-s : ℤ) * x⁻¹ * y ^ (s : ℤ) * x) (y⁻¹ * x * y ^ (-s : ℤ) * x⁻¹ * x⁻¹ * y ^ (s : ℤ) * x)) 1
      (pair (y ^ (-s : ℤ) * x * y ^ (-s : ℤ) * x⁻¹ * y ^ (s : ℤ) * x * y⁻¹) (y⁻¹ * x * y ^ (-s : ℤ) * x⁻¹ * x⁻¹ * y ^ (s : ℤ) * x)) :=
    conj0 _ _ (y) _ (by group)
  have h9 : Steps (pair (y ^ (-s : ℤ) * x * y ^ (-s : ℤ) * x⁻¹ * y ^ (s : ℤ) * x * y⁻¹) (y⁻¹ * x * y ^ (-s : ℤ) * x⁻¹ * x⁻¹ * y ^ (s : ℤ) * x)) 1
      (pair (y ^ (-s : ℤ) * x * y ^ (-s : ℤ) * x⁻¹ * y ^ (s : ℤ) * x * y⁻¹) (x * y ^ (-s : ℤ) * x⁻¹ * x⁻¹ * y ^ (s : ℤ) * x * y⁻¹)) :=
    conj1 _ _ (y) _ (by group)
  have h10 : Steps (pair (y ^ (-s : ℤ) * x * y ^ (-s : ℤ) * x⁻¹ * y ^ (s : ℤ) * x * y⁻¹) (x * y ^ (-s : ℤ) * x⁻¹ * x⁻¹ * y ^ (s : ℤ) * x * y⁻¹)) 3
      (pair (y ^ (-s : ℤ) * x * y ^ (-s : ℤ) * x * y ^ (s : ℤ) * x⁻¹) (x * y ^ (-s : ℤ) * x⁻¹ * x⁻¹ * y ^ (s : ℤ) * x * y⁻¹)) :=
    neg0 _ _ _ (by group)
  have h11 : Steps (pair (y ^ (-s : ℤ) * x * y ^ (-s : ℤ) * x * y ^ (s : ℤ) * x⁻¹) (x * y ^ (-s : ℤ) * x⁻¹ * x⁻¹ * y ^ (s : ℤ) * x * y⁻¹)) 1
      (pair (x * y ^ (-s : ℤ) * x⁻¹ * y ^ (s : ℤ) * x⁻¹ * y ^ (s : ℤ)) (x * y ^ (-s : ℤ) * x⁻¹ * x⁻¹ * y ^ (s : ℤ) * x * y⁻¹)) :=
    inv0 _ _ _ (by group)
  have h12 : Steps (pair (x * y ^ (-s : ℤ) * x⁻¹ * y ^ (s : ℤ) * x⁻¹ * y ^ (s : ℤ)) (x * y ^ (-s : ℤ) * x⁻¹ * x⁻¹ * y ^ (s : ℤ) * x * y⁻¹)) 1
      (pair (y ^ (-s : ℤ) * x⁻¹ * y ^ (s : ℤ) * x⁻¹ * y ^ (s : ℤ) * x) (x * y ^ (-s : ℤ) * x⁻¹ * x⁻¹ * y ^ (s : ℤ) * x * y⁻¹)) :=
    conj0 _ _ (x⁻¹) _ (by group)
  have h13 : Steps (pair (y ^ (-s : ℤ) * x⁻¹ * y ^ (s : ℤ) * x⁻¹ * y ^ (s : ℤ) * x) (x * y ^ (-s : ℤ) * x⁻¹ * x⁻¹ * y ^ (s : ℤ) * x * y⁻¹)) 1
      (pair (y ^ (-s : ℤ) * x⁻¹ * y ^ (s : ℤ) * x⁻¹ * y ^ (s : ℤ) * x) (y⁻¹ * x * y ^ (-s : ℤ) * x⁻¹ * x⁻¹ * y ^ (s : ℤ) * x)) :=
    conj1 _ _ (y⁻¹) _ (by group)
  have h14 : Steps (pair (y ^ (-s : ℤ) * x⁻¹ * y ^ (s : ℤ) * x⁻¹ * y ^ (s : ℤ) * x) (y⁻¹ * x * y ^ (-s : ℤ) * x⁻¹ * x⁻¹ * y ^ (s : ℤ) * x)) 3
      (pair (y ^ (-s : ℤ) * x⁻¹ * y ^ (s : ℤ) * x⁻¹ * y ^ (s : ℤ) * x) (y⁻¹ * x * y ^ (-s : ℤ) * x⁻¹ * y ^ (-s : ℤ) * x * y ^ (s : ℤ))) :=
    neg1 _ _ _ (by group)
  have h15 : Steps (pair (y ^ (-s : ℤ) * x⁻¹ * y ^ (s : ℤ) * x⁻¹ * y ^ (s : ℤ) * x) (y⁻¹ * x * y ^ (-s : ℤ) * x⁻¹ * y ^ (-s : ℤ) * x * y ^ (s : ℤ))) 1
      (pair (y ^ (-s : ℤ) * x⁻¹ * y ^ (s : ℤ) * x⁻¹ * y ^ (s : ℤ) * x) (y ^ (-s : ℤ) * x⁻¹ * y ^ (-s : ℤ) * x * y ^ (s - 1 : ℤ) * x)) :=
    conj1 _ _ (x⁻¹ * y) _ (by group)
  have h16 : Steps (pair (y ^ (-s : ℤ) * x⁻¹ * y ^ (s : ℤ) * x⁻¹ * y ^ (s : ℤ) * x) (y ^ (-s : ℤ) * x⁻¹ * y ^ (-s : ℤ) * x * y ^ (s - 1 : ℤ) * x)) 3
      (pair (y ^ (-s : ℤ) * x⁻¹ * y ^ (s : ℤ) * x⁻¹ * y ^ (s : ℤ) * x) (y ^ (-s : ℤ) * x⁻¹ * y ^ (-s : ℤ) * x * y⁻¹ * x * y ^ (-s : ℤ) * x * y ^ (s : ℤ))) :=
    neg1 _ _ _ (by group)
  have h17 : Steps (pair (y ^ (-s : ℤ) * x⁻¹ * y ^ (s : ℤ) * x⁻¹ * y ^ (s : ℤ) * x) (y ^ (-s : ℤ) * x⁻¹ * y ^ (-s : ℤ) * x * y⁻¹ * x * y ^ (-s : ℤ) * x * y ^ (s : ℤ))) 1
      (pair (y ^ (-s : ℤ) * x⁻¹ * y ^ (s : ℤ) * x⁻¹ * y ^ (s : ℤ) * x) (x⁻¹ * y ^ (-s : ℤ) * x * y⁻¹ * x * y ^ (-s : ℤ) * x)) :=
    conj1 _ _ (y ^ (s : ℤ)) _ (by group)
  have h18 : Steps (pair (y ^ (-s : ℤ) * x⁻¹ * y ^ (s : ℤ) * x⁻¹ * y ^ (s : ℤ) * x) (x⁻¹ * y ^ (-s : ℤ) * x * y⁻¹ * x * y ^ (-s : ℤ) * x)) 1
      (pair (y ^ (-s : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x * y ^ (-s : ℤ) * x) (x⁻¹ * y ^ (-s : ℤ) * x * y⁻¹ * x * y ^ (-s : ℤ) * x)) :=
    mul0 _ _ _ (by group)
  have h19 : Steps (pair (y ^ (-s : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x * y ^ (-s : ℤ) * x) (x⁻¹ * y ^ (-s : ℤ) * x * y⁻¹ * x * y ^ (-s : ℤ) * x)) 1
      (pair (y ^ (-s : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x * y ^ (-s : ℤ) * x) (y⁻¹ * x * y ^ (-2 * s : ℤ) * x)) :=
    conj1 _ _ (y⁻¹ * x * y ^ (-s : ℤ) * x) _ (by group)
  have h20 : Steps (pair (y ^ (-s : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x * y ^ (-s : ℤ) * x) (y⁻¹ * x * y ^ (-2 * s : ℤ) * x)) 3
      (pair (y ^ (-s : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x * y ^ (-s : ℤ) * x) (y⁻¹ * x * y ^ (-s : ℤ) * x⁻¹ * y ^ (-s + 1 : ℤ) * x * y ^ (s : ℤ))) :=
    neg1 _ _ _ (by group)
  have h21 : Steps (pair (y ^ (-s : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x * y ^ (-s : ℤ) * x) (y⁻¹ * x * y ^ (-s : ℤ) * x⁻¹ * y ^ (-s + 1 : ℤ) * x * y ^ (s : ℤ))) 1
      (pair (y ^ (-s : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x * y ^ (-s : ℤ) * x) (y ^ (-s : ℤ) * x⁻¹ * y ^ (-s + 1 : ℤ) * x * y ^ (s - 1 : ℤ) * x)) :=
    conj1 _ _ (x⁻¹ * y) _ (by group)
  have h22 : Steps (pair (y ^ (-s : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x * y ^ (-s : ℤ) * x) (y ^ (-s : ℤ) * x⁻¹ * y ^ (-s + 1 : ℤ) * x * y ^ (s - 1 : ℤ) * x)) 1
      (pair (y ^ (-s : ℤ) * x * y ^ (-s : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x) (y ^ (-s : ℤ) * x⁻¹ * y ^ (-s + 1 : ℤ) * x * y ^ (s - 1 : ℤ) * x)) :=
    conj0 _ _ (y ^ (-s : ℤ) * x) _ (by group)
  have h23 : Steps (pair (y ^ (-s : ℤ) * x * y ^ (-s : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x) (y ^ (-s : ℤ) * x⁻¹ * y ^ (-s + 1 : ℤ) * x * y ^ (s - 1 : ℤ) * x)) 3
      (pair (y ^ (-s : ℤ) * x * y ^ (-s : ℤ) * x⁻¹ * x⁻¹ * y ^ (s - 1 : ℤ) * x * y ^ (s : ℤ)) (y ^ (-s : ℤ) * x⁻¹ * y ^ (-s + 1 : ℤ) * x * y ^ (s - 1 : ℤ) * x)) :=
    neg0 _ _ _ (by group)
  have h24 : Steps (pair (y ^ (-s : ℤ) * x * y ^ (-s : ℤ) * x⁻¹ * x⁻¹ * y ^ (s - 1 : ℤ) * x * y ^ (s : ℤ)) (y ^ (-s : ℤ) * x⁻¹ * y ^ (-s + 1 : ℤ) * x * y ^ (s - 1 : ℤ) * x)) 1
      (pair (y ^ (-s : ℤ) * x⁻¹ * x⁻¹ * y ^ (s - 1 : ℤ) * x * x) (y ^ (-s : ℤ) * x⁻¹ * y ^ (-s + 1 : ℤ) * x * y ^ (s - 1 : ℤ) * x)) :=
    conj0 _ _ (x⁻¹ * y ^ (s : ℤ)) _ (by group)
  have h25 : Steps (pair (y ^ (-s : ℤ) * x⁻¹ * x⁻¹ * y ^ (s - 1 : ℤ) * x * x) (y ^ (-s : ℤ) * x⁻¹ * y ^ (-s + 1 : ℤ) * x * y ^ (s - 1 : ℤ) * x)) 3
      (pair (y ^ (-s : ℤ) * x⁻¹ * x⁻¹ * y ^ (s - 1 : ℤ) * x * y ^ (-s + 1 : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x * y ^ (s : ℤ)) (y ^ (-s : ℤ) * x⁻¹ * y ^ (-s + 1 : ℤ) * x * y ^ (s - 1 : ℤ) * x)) :=
    neg0 _ _ _ (by group)
  have h26 : Steps (pair (y ^ (-s : ℤ) * x⁻¹ * x⁻¹ * y ^ (s - 1 : ℤ) * x * y ^ (-s + 1 : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x * y ^ (s : ℤ)) (y ^ (-s : ℤ) * x⁻¹ * y ^ (-s + 1 : ℤ) * x * y ^ (s - 1 : ℤ) * x)) 1
      (pair (y ^ (-s + 1 : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x) (y ^ (-s : ℤ) * x⁻¹ * y ^ (-s + 1 : ℤ) * x * y ^ (s - 1 : ℤ) * x)) :=
    conj0 _ _ (x⁻¹ * y ^ (-s + 1 : ℤ) * x * x * y ^ (s : ℤ)) _ (by group)
  have h27 : Steps (pair (y ^ (-s + 1 : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x) (y ^ (-s : ℤ) * x⁻¹ * y ^ (-s + 1 : ℤ) * x * y ^ (s - 1 : ℤ) * x)) 3
      (pair (y ^ (-s + 1 : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x) (y ^ (-s : ℤ) * x⁻¹ * y ^ (-s + 1 : ℤ) * x * x * y ^ (-s + 1 : ℤ) * x * y ^ (s - 1 : ℤ))) :=
    neg1 _ _ _ (by group)
  have h28 : Steps (pair (y ^ (-s + 1 : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x) (y ^ (-s : ℤ) * x⁻¹ * y ^ (-s + 1 : ℤ) * x * x * y ^ (-s + 1 : ℤ) * x * y ^ (s - 1 : ℤ))) 1
      (pair (y ^ (-s + 1 : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x) (x⁻¹ * y ^ (-s + 1 : ℤ) * x * x * y ^ (-s + 1 : ℤ) * x * y⁻¹)) :=
    conj1 _ _ (y ^ (s : ℤ)) _ (by group)
  have h29 : Steps (pair (y ^ (-s + 1 : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x) (x⁻¹ * y ^ (-s + 1 : ℤ) * x * x * y ^ (-s + 1 : ℤ) * x * y⁻¹)) 1
      (pair (y ^ (-s + 1 : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x) (x⁻¹ * y ^ (-s + 1 : ℤ) * x * x * y ^ (-s + 1 : ℤ) * x * y ^ (-s : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x)) :=
    mul1 _ _ _ (by group)
  have h30 : Steps (pair (y ^ (-s + 1 : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x) (x⁻¹ * y ^ (-s + 1 : ℤ) * x * x * y ^ (-s + 1 : ℤ) * x * y ^ (-s : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x)) 1
      (pair (y ^ (-s + 1 : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x) (y ^ (-s + 1 : ℤ) * x * y ^ (-s : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x)) :=
    conj1 _ _ (x⁻¹ * x⁻¹ * y ^ (s - 1 : ℤ) * x) _ (by group)
  have h31 : Steps (pair (y ^ (-s + 1 : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x) (y ^ (-s + 1 : ℤ) * x * y ^ (-s : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x)) 3
      (pair (y ^ (-s + 1 : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x) (y ^ (-s + 1 : ℤ) * x * y ^ (-2 * s + 1 : ℤ) * x * y ^ (s - 1 : ℤ))) :=
    neg1 _ _ _ (by group)
  have h32 : Steps (pair (y ^ (-s + 1 : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x) (y ^ (-s + 1 : ℤ) * x * y ^ (-2 * s + 1 : ℤ) * x * y ^ (s - 1 : ℤ))) 1
      (pair (y ^ (-s + 1 : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x) (y ^ (-2 * s + 1 : ℤ) * x * x)) :=
    conj1 _ _ (x⁻¹ * y ^ (s - 1 : ℤ)) _ (by group)
  have h33 : Steps (pair (y ^ (-s + 1 : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x) (y ^ (-2 * s + 1 : ℤ) * x * x)) 1
      (pair (y ^ (-s + 1 : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x * y ^ (-2 * s + 1 : ℤ) * x * x) (y ^ (-2 * s + 1 : ℤ) * x * x)) :=
    mul0 _ _ _ (by group)
  have h34 : Steps (pair (y ^ (-s + 1 : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x * y ^ (-2 * s + 1 : ℤ) * x * x) (y ^ (-2 * s + 1 : ℤ) * x * x)) 1
      (pair (x⁻¹ * x⁻¹ * y ^ (2 * s - 1 : ℤ) * x⁻¹ * y ^ (-s + 1 : ℤ) * x * y ^ (-s + 1 : ℤ) * x * y ^ (s - 1 : ℤ)) (y ^ (-2 * s + 1 : ℤ) * x * x)) :=
    inv0 _ _ _ (by group)
  have h35 : Steps (pair (x⁻¹ * x⁻¹ * y ^ (2 * s - 1 : ℤ) * x⁻¹ * y ^ (-s + 1 : ℤ) * x * y ^ (-s + 1 : ℤ) * x * y ^ (s - 1 : ℤ)) (y ^ (-2 * s + 1 : ℤ) * x * x)) 1
      (pair (x⁻¹ * x⁻¹ * y ^ (2 * s - 1 : ℤ) * x⁻¹ * y ^ (-s + 1 : ℤ) * x * y ^ (-s + 1 : ℤ) * x * y ^ (s - 1 : ℤ)) (x⁻¹ * y ^ (-s + 1 : ℤ) * x * y ^ (-s + 1 : ℤ) * x * y ^ (s - 1 : ℤ))) :=
    mul1 _ _ _ (by group)
  have h36 : Steps (pair (x⁻¹ * x⁻¹ * y ^ (2 * s - 1 : ℤ) * x⁻¹ * y ^ (-s + 1 : ℤ) * x * y ^ (-s + 1 : ℤ) * x * y ^ (s - 1 : ℤ)) (x⁻¹ * y ^ (-s + 1 : ℤ) * x * y ^ (-s + 1 : ℤ) * x * y ^ (s - 1 : ℤ))) 1
      (pair (y ^ (-s + 1 : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x * y ^ (-2 * s + 1 : ℤ) * x * x) (x⁻¹ * y ^ (-s + 1 : ℤ) * x * y ^ (-s + 1 : ℤ) * x * y ^ (s - 1 : ℤ))) :=
    inv0 _ _ _ (by group; simp only [zpow_ofNat, pow_two, mul_assoc])
  have h37 : Steps (pair (y ^ (-s + 1 : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x * y ^ (-2 * s + 1 : ℤ) * x * x) (x⁻¹ * y ^ (-s + 1 : ℤ) * x * y ^ (-s + 1 : ℤ) * x * y ^ (s - 1 : ℤ))) 1
      (pair (y ^ (-2 * s + 1 : ℤ) * x * x * y ^ (-s + 1 : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x) (x⁻¹ * y ^ (-s + 1 : ℤ) * x * y ^ (-s + 1 : ℤ) * x * y ^ (s - 1 : ℤ))) :=
    conj0 _ _ (x⁻¹ * y ^ (-s + 1 : ℤ) * x * y ^ (-s + 1 : ℤ) * x * y ^ (s - 1 : ℤ)) _ (by group)
  have h38 : Steps (pair (y ^ (-2 * s + 1 : ℤ) * x * x * y ^ (-s + 1 : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x) (x⁻¹ * y ^ (-s + 1 : ℤ) * x * y ^ (-s + 1 : ℤ) * x * y ^ (s - 1 : ℤ))) 1
      (pair (y ^ (-2 * s + 1 : ℤ) * x * x) (x⁻¹ * y ^ (-s + 1 : ℤ) * x * y ^ (-s + 1 : ℤ) * x * y ^ (s - 1 : ℤ))) :=
    mul0 _ _ _ (by group)
  have h39 : Steps (pair (y ^ (-2 * s + 1 : ℤ) * x * x) (x⁻¹ * y ^ (-s + 1 : ℤ) * x * y ^ (-s + 1 : ℤ) * x * y ^ (s - 1 : ℤ))) 1
      (pair (y ^ (-2 * s + 1 : ℤ) * x * x) (y ^ (-s + 1 : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x)) :=
    inv1 _ _ _ (by group)
  have h40 : Steps (pair (y ^ (-2 * s + 1 : ℤ) * x * x) (y ^ (-s + 1 : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x)) 1
      (pair (x * x * y ^ (-2 * s + 1 : ℤ)) (y ^ (-s + 1 : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x)) :=
    conj0 _ _ (x * x) _ (by group)
  have h41 : Steps (pair (x * x * y ^ (-2 * s + 1 : ℤ)) (y ^ (-s + 1 : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x)) 1
      (pair (x * x * y ^ (-2 * s + 1 : ℤ)) (x⁻¹ * y ^ (s - 1 : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x * y ^ (-s + 1 : ℤ))) :=
    conj1 _ _ (y ^ (s - 1 : ℤ)) _ (by group)
  have h42 : Steps (pair (x * x * y ^ (-2 * s + 1 : ℤ)) (x⁻¹ * y ^ (s - 1 : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x * y ^ (-s + 1 : ℤ))) 1
      (pair (y ^ (s - 1 : ℤ) * x⁻¹ * y ^ (-s + 1 : ℤ) * x * x * y ^ (-s : ℤ) * x * y ^ (-s + 1 : ℤ)) (x⁻¹ * y ^ (s - 1 : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x * y ^ (-s + 1 : ℤ))) :=
    conj0 _ _ (y ^ (s - 1 : ℤ) * x⁻¹ * y ^ (-s + 1 : ℤ)) _ (by group)
  have h43 : Steps (pair (y ^ (s - 1 : ℤ) * x⁻¹ * y ^ (-s + 1 : ℤ) * x * x * y ^ (-s : ℤ) * x * y ^ (-s + 1 : ℤ)) (x⁻¹ * y ^ (s - 1 : ℤ) * x⁻¹ * y ^ (s - 1 : ℤ) * x * y ^ (-s + 1 : ℤ))) 1
      (pair (y ^ (s - 1 : ℤ) * x⁻¹ * y ^ (-s + 1 : ℤ) * x * x * y ^ (-s : ℤ) * x * y ^ (-s + 1 : ℤ)) (x⁻¹ * y ^ (s - 1 : ℤ) * x * y ^ (-s : ℤ) * x * y ^ (-s + 1 : ℤ))) :=
    mul1 _ _ _ (by group)
  have h44 : Steps (pair (y ^ (s - 1 : ℤ) * x⁻¹ * y ^ (-s + 1 : ℤ) * x * x * y ^ (-s : ℤ) * x * y ^ (-s + 1 : ℤ)) (x⁻¹ * y ^ (s - 1 : ℤ) * x * y ^ (-s : ℤ) * x * y ^ (-s + 1 : ℤ))) 1
      (pair (x * x * y ^ (-2 * s + 1 : ℤ)) (x⁻¹ * y ^ (s - 1 : ℤ) * x * y ^ (-s : ℤ) * x * y ^ (-s + 1 : ℤ))) :=
    conj0 _ _ (y ^ (s - 1 : ℤ) * x * y ^ (-s + 1 : ℤ)) _ (by group)
  have h45 : Steps (pair (x * x * y ^ (-2 * s + 1 : ℤ)) (x⁻¹ * y ^ (s - 1 : ℤ) * x * y ^ (-s : ℤ) * x * y ^ (-s + 1 : ℤ))) 1
      (pair (y ^ (s - 1 : ℤ) * x * y ^ (-2 * s + 1 : ℤ) * x * y ^ (-s + 1 : ℤ)) (x⁻¹ * y ^ (s - 1 : ℤ) * x * y ^ (-s : ℤ) * x * y ^ (-s + 1 : ℤ))) :=
    conj0 _ _ (y ^ (s - 1 : ℤ) * x⁻¹) _ (by group)
  have h46 : Steps (pair (y ^ (s - 1 : ℤ) * x * y ^ (-2 * s + 1 : ℤ) * x * y ^ (-s + 1 : ℤ)) (x⁻¹ * y ^ (s - 1 : ℤ) * x * y ^ (-s : ℤ) * x * y ^ (-s + 1 : ℤ))) 3
      (pair (y ^ (s - 1 : ℤ) * x * y ^ (-2 * s + 1 : ℤ) * x * y ^ (-s + 1 : ℤ)) (x⁻¹ * y ^ (s - 1 : ℤ) * x * y ^ (s - 1 : ℤ) * x⁻¹ * y ^ (-s + 1 : ℤ))) :=
    neg1 _ _ _ (by group)
  have h47 : Steps (pair (y ^ (s - 1 : ℤ) * x * y ^ (-2 * s + 1 : ℤ) * x * y ^ (-s + 1 : ℤ)) (x⁻¹ * y ^ (s - 1 : ℤ) * x * y ^ (s - 1 : ℤ) * x⁻¹ * y ^ (-s + 1 : ℤ))) 1
      (pair (x * x * y ^ (-2 * s + 1 : ℤ)) (x⁻¹ * y ^ (s - 1 : ℤ) * x * y ^ (s - 1 : ℤ) * x⁻¹ * y ^ (-s + 1 : ℤ))) :=
    conj0 _ _ (x * y ^ (-s + 1 : ℤ)) _ (by group)
  have h48 : Steps (pair (x * x * y ^ (-2 * s + 1 : ℤ)) (x⁻¹ * y ^ (s - 1 : ℤ) * x * y ^ (s - 1 : ℤ) * x⁻¹ * y ^ (-s + 1 : ℤ))) 1
      (pair (x * x * y ^ (-2 * s + 1 : ℤ)) (y ^ (s - 1 : ℤ) * x * y ^ (s - 1 : ℤ) * x⁻¹ * y ^ (-s + 1 : ℤ) * x⁻¹)) :=
    conj1 _ _ (x) _ (by group)
  have h49 : Steps (pair (x * x * y ^ (-2 * s + 1 : ℤ)) (y ^ (s - 1 : ℤ) * x * y ^ (s - 1 : ℤ) * x⁻¹ * y ^ (-s + 1 : ℤ) * x⁻¹)) 1
      (pair (x * x * y ^ (-2 * s + 1 : ℤ)) (x * y ^ (s - 1 : ℤ) * x * y ^ (-s + 1 : ℤ) * x⁻¹ * y ^ (-s + 1 : ℤ))) :=
    inv1 _ _ _ (by group)
  have he : diagonal (s - 1) = pair (x * x * y ^ (-2 * s + 1 : ℤ)) (x * y ^ (s - 1 : ℤ) * x * y ^ (-s + 1 : ℤ) * x⁻¹ * y ^ (-s + 1 : ℤ)) := by
    ext i
    fin_cases i <;> simp [diagonal, square, relation, pair, pow_two] <;> group
  rw [hi, he]
  exact ((((((((((((((((((((((((((((((((((((((((((((((((h1.trans h2).trans h3).trans h4).trans h5).trans h6).trans h7).trans h8).trans h9).trans h10).trans h11).trans h12).trans h13).trans h14).trans h15).trans h16).trans h17).trans h18).trans h19).trans h20).trans h21).trans h22).trans h23).trans h24).trans h25).trans h26).trans h27).trans h28).trans h29).trans h30).trans h31).trans h32).trans h33).trans h34).trans h35).trans h36).trans h37).trans h38).trans h39).trans h40).trans h41).trans h42).trans h43).trans h44).trans h45).trans h46).trans h47).trans h48).trans h49)

/-- The zero parameter has a direct 15-primitive finish. -/
theorem base : Steps (diagonal 0) 15 (standard 2) := by
  have hi : diagonal 0 = pair (x * x * y⁻¹) (x) := by
    ext i
    fin_cases i <;> simp [diagonal, square, relation, pair, pow_two]
  have h1 : Steps (pair (x * x * y⁻¹) (x)) 1
      (pair (y⁻¹ * x * x) (x)) :=
    conj0 _ _ (x⁻¹ * x⁻¹) _ (by group; simp only [zpow_ofNat, pow_two, mul_assoc])
  have h2 : Steps (pair (y⁻¹ * x * x) (x)) 3
      (pair (y⁻¹ * x) (x)) :=
    neg0 _ _ _ (by group)
  have h3 : Steps (pair (y⁻¹ * x) (x)) 3
      (pair (y⁻¹) (x)) :=
    neg0 _ _ _ (by group)
  have h4 : Steps (pair (y⁻¹) (x)) 1
      (pair (y) (x)) :=
    inv0 _ _ _ (by group)
  have h5 : Steps (pair (y) (x)) 1
      (pair (y * x) (x)) :=
    mul0 _ _ _ (by group)
  have h6 : Steps (pair (y * x) (x)) 1
      (pair (x⁻¹ * y⁻¹) (x)) :=
    inv0 _ _ _ (by group)
  have h7 : Steps (pair (x⁻¹ * y⁻¹) (x)) 1
      (pair (x⁻¹ * y⁻¹) (y⁻¹)) :=
    mul1 _ _ _ (by group)
  have h8 : Steps (pair (x⁻¹ * y⁻¹) (y⁻¹)) 1
      (pair (y * x) (y⁻¹)) :=
    inv0 _ _ _ (by group)
  have h9 : Steps (pair (y * x) (y⁻¹)) 1
      (pair (x * y) (y⁻¹)) :=
    conj0 _ _ (y⁻¹) _ (by group)
  have h10 : Steps (pair (x * y) (y⁻¹)) 1
      (pair (x) (y⁻¹)) :=
    mul0 _ _ _ (by group)
  have h11 : Steps (pair (x) (y⁻¹)) 1
      (pair (x) (y)) :=
    inv1 _ _ _ (by group)
  have he : standard 2 = pair (x) (y) := by
    ext i
    fin_cases i <;> simp [pair, standard, x, y]
  rw [hi, he]
  exact ((((((((((h1.trans h2).trans h3).trans h4).trans h5).trans h6).trans h7).trans h8).trans h9).trans h10).trans h11)

/-- The recurrence gives a linear bound in the official mathematical primitives. -/
theorem counted (s : ℕ) : Steps (diagonal s) (71 * s + 15) (standard 2) := by
  induction s with
  | zero => simpa using base
  | succ s ih =>
    have hd : Steps (diagonal ((s + 1 : ℕ) : ℤ)) 71 (diagonal s) := by
      simpa using descent ((s : ℤ) + 1)
    convert hd.trans ih using 1
    omega

theorem solvable (s : ℕ) : Reachable (diagonal s) (standard 2) := (counted s).reachable

end AC.MillerSchupp.SquareFamily.Diagonal
