import ACSquareP2Root

/-! Exact ordinary entry into the root family for every integer p,s.
The degree-two root family is solved in the imported module. Generated by
research/p2-family/generate_entry.py; Lean checks every free-group identity. -/

namespace AC.MillerSchupp.SquareFamily.P2
open AC.Certificate AC.WordTransport

def entryMap (p s : ℤ) : Word 2 →* Word 2 :=
  FreeGroup.lift (pair (y ^ (s + 1 - p) * x⁻¹ * y ^ p) y⁻¹)

@[simp] theorem entryMap_x (p s : ℤ) :
    entryMap p s x = y ^ (s + 1 - p) * x⁻¹ * y ^ p := by
  simp [entryMap, x, pair]

@[simp] theorem entryMap_y (p s : ℤ) : entryMap p s y = y⁻¹ := by
  simp [entryMap, y, pair]

private theorem conj0 (r q g z : Word 2)
    (he : g * r * g⁻¹ = z) : Steps (pair r q) 1 (pair z q) := by
  simpa only [pair_zero, pair_one, he, pair_update_zero] using
    Steps.single (Step.conj (pair r q) 0 g)

private theorem conj1 (r q g z : Word 2)
    (he : g * q * g⁻¹ = z) : Steps (pair r q) 1 (pair r z) := by
  simpa only [pair_zero, pair_one, he, pair_update_one] using
    Steps.single (Step.conj (pair r q) 1 g)

private theorem inv0 (r q z : Word 2)
    (he : r⁻¹ = z) : Steps (pair r q) 1 (pair z q) := by
  simpa only [pair_zero, pair_one, he, pair_update_zero] using
    Steps.single (Step.inv (pair r q) 0)

private theorem inv1 (r q z : Word 2)
    (he : q⁻¹ = z) : Steps (pair r q) 1 (pair r z) := by
  simpa only [pair_zero, pair_one, he, pair_update_one] using
    Steps.single (Step.inv (pair r q) 1)

private theorem mul0 (r q z : Word 2)
    (he : r * q = z) : Steps (pair r q) 1 (pair z q) := by
  simpa only [pair_zero, pair_one, he, pair_update_zero] using
    Steps.single (Step.mulRight (pair r q) 0 1 (by decide))

private theorem mul1 (r q z : Word 2)
    (he : q * r = z) : Steps (pair r q) 1 (pair r z) := by
  simpa only [pair_zero, pair_one, he, pair_update_one] using
    Steps.single (Step.mulRight (pair r q) 1 0 (by decide))

private theorem neg0 (r q z : Word 2)
    (he : r * q⁻¹ = z) : Steps (pair r q) 3 (pair z q) := by
  simpa only [pair_zero, pair_one, he, pair_update_zero] using
    Steps.mulInvRight (pair r q) 0 1 (by decide)

private theorem neg1 (r q z : Word 2)
    (he : q * r⁻¹ = z) : Steps (pair r q) 3 (pair r z) := by
  simpa only [pair_zero, pair_one, he, pair_update_one] using
    Steps.mulInvRight (pair r q) 1 0 (by decide)

theorem root_entry (p s : ℤ) :
    Steps (Diagonal.normalForm p s) 43
      (applyHom (entryMap p s) (pair (root p) (companion s))) := by
  have hi : Diagonal.normalForm p s = pair (y ^ (-p : ℤ) * x⁻¹ * y ^ (p : ℤ) * x⁻¹ * y ^ (s : ℤ) * x) (x * y ^ (-p : ℤ) * x⁻¹ * x⁻¹ * y ^ (p : ℤ) * x * y⁻¹) := by
    ext i
    fin_cases i <;> simp [Diagonal.normalForm, pair]
  have h1 : Steps (pair (y ^ (-p : ℤ) * x⁻¹ * y ^ (p : ℤ) * x⁻¹ * y ^ (s : ℤ) * x) (x * y ^ (-p : ℤ) * x⁻¹ * x⁻¹ * y ^ (p : ℤ) * x * y⁻¹)) 1
      (pair (x⁻¹ * y ^ (-s : ℤ) * x * y ^ (-p : ℤ) * x * y ^ (p : ℤ)) (x * y ^ (-p : ℤ) * x⁻¹ * x⁻¹ * y ^ (p : ℤ) * x * y⁻¹)) :=
    inv0 _ _ _ (by group)
  have h2 : Steps (pair (x⁻¹ * y ^ (-s : ℤ) * x * y ^ (-p : ℤ) * x * y ^ (p : ℤ)) (x * y ^ (-p : ℤ) * x⁻¹ * x⁻¹ * y ^ (p : ℤ) * x * y⁻¹)) 1
      (pair (x * y ^ (p : ℤ) * x⁻¹ * y ^ (-s : ℤ) * x * y ^ (-p : ℤ)) (x * y ^ (-p : ℤ) * x⁻¹ * x⁻¹ * y ^ (p : ℤ) * x * y⁻¹)) :=
    conj0 _ _ (y ^ (p : ℤ) * x⁻¹ * y ^ (s : ℤ) * x) _ (by group)
  have h3 : Steps (pair (x * y ^ (p : ℤ) * x⁻¹ * y ^ (-s : ℤ) * x * y ^ (-p : ℤ)) (x * y ^ (-p : ℤ) * x⁻¹ * x⁻¹ * y ^ (p : ℤ) * x * y⁻¹)) 1
      (pair (x * y ^ (p : ℤ) * x⁻¹ * y ^ (-s : ℤ) * x * y ^ (-p : ℤ)) (y * x⁻¹ * y ^ (-p : ℤ) * x * x * y ^ (p : ℤ) * x⁻¹)) :=
    inv1 _ _ _ (by group; simp only [zpow_ofNat, pow_two, mul_assoc])
  have h4 : Steps (pair (x * y ^ (p : ℤ) * x⁻¹ * y ^ (-s : ℤ) * x * y ^ (-p : ℤ)) (y * x⁻¹ * y ^ (-p : ℤ) * x * x * y ^ (p : ℤ) * x⁻¹)) 1
      (pair (x * y ^ (p : ℤ) * x⁻¹ * y ^ (-s : ℤ) * x * y ^ (-p : ℤ)) (x * x * y ^ (p : ℤ) * x⁻¹ * y * x⁻¹ * y ^ (-p : ℤ))) :=
    conj1 _ _ (y ^ (p : ℤ) * x * y⁻¹) _ (by group)
  have h5 : Steps (pair (x * y ^ (p : ℤ) * x⁻¹ * y ^ (-s : ℤ) * x * y ^ (-p : ℤ)) (x * x * y ^ (p : ℤ) * x⁻¹ * y * x⁻¹ * y ^ (-p : ℤ))) 1
      (pair (x * y ^ (p : ℤ) * x⁻¹ * y ^ (-s : ℤ) * x * y ^ (-p : ℤ) * x * x * y ^ (p : ℤ) * x⁻¹ * y * x⁻¹ * y ^ (-p : ℤ)) (x * x * y ^ (p : ℤ) * x⁻¹ * y * x⁻¹ * y ^ (-p : ℤ))) :=
    mul0 _ _ _ (by group)
  have h6 : Steps (pair (x * y ^ (p : ℤ) * x⁻¹ * y ^ (-s : ℤ) * x * y ^ (-p : ℤ) * x * x * y ^ (p : ℤ) * x⁻¹ * y * x⁻¹ * y ^ (-p : ℤ)) (x * x * y ^ (p : ℤ) * x⁻¹ * y * x⁻¹ * y ^ (-p : ℤ))) 1
      (pair (y ^ (p : ℤ) * x * y⁻¹ * x * y ^ (-p : ℤ) * x⁻¹ * x⁻¹ * y ^ (p : ℤ) * x⁻¹ * y ^ (s : ℤ) * x * y ^ (-p : ℤ) * x⁻¹) (x * x * y ^ (p : ℤ) * x⁻¹ * y * x⁻¹ * y ^ (-p : ℤ))) :=
    inv0 _ _ _ (by group)
  have h7 : Steps (pair (y ^ (p : ℤ) * x * y⁻¹ * x * y ^ (-p : ℤ) * x⁻¹ * x⁻¹ * y ^ (p : ℤ) * x⁻¹ * y ^ (s : ℤ) * x * y ^ (-p : ℤ) * x⁻¹) (x * x * y ^ (p : ℤ) * x⁻¹ * y * x⁻¹ * y ^ (-p : ℤ))) 1
      (pair (y ^ (p : ℤ) * x * y⁻¹ * x * y ^ (-p : ℤ) * x⁻¹ * x⁻¹ * y ^ (p : ℤ) * x⁻¹ * y ^ (s : ℤ) * x * y ^ (-p : ℤ) * x⁻¹) (y ^ (p : ℤ) * x⁻¹ * y ^ (s : ℤ) * x * y ^ (-p : ℤ) * x⁻¹)) :=
    mul1 _ _ _ (by group)
  have h8 : Steps (pair (y ^ (p : ℤ) * x * y⁻¹ * x * y ^ (-p : ℤ) * x⁻¹ * x⁻¹ * y ^ (p : ℤ) * x⁻¹ * y ^ (s : ℤ) * x * y ^ (-p : ℤ) * x⁻¹) (y ^ (p : ℤ) * x⁻¹ * y ^ (s : ℤ) * x * y ^ (-p : ℤ) * x⁻¹)) 1
      (pair (x * y ^ (p : ℤ) * x⁻¹ * y ^ (-s : ℤ) * x * y ^ (-p : ℤ) * x * x * y ^ (p : ℤ) * x⁻¹ * y * x⁻¹ * y ^ (-p : ℤ)) (y ^ (p : ℤ) * x⁻¹ * y ^ (s : ℤ) * x * y ^ (-p : ℤ) * x⁻¹)) :=
    inv0 _ _ _ (by group; simp only [zpow_ofNat, pow_two, mul_assoc])
  have h9 : Steps (pair (x * y ^ (p : ℤ) * x⁻¹ * y ^ (-s : ℤ) * x * y ^ (-p : ℤ) * x * x * y ^ (p : ℤ) * x⁻¹ * y * x⁻¹ * y ^ (-p : ℤ)) (y ^ (p : ℤ) * x⁻¹ * y ^ (s : ℤ) * x * y ^ (-p : ℤ) * x⁻¹)) 1
      (pair (x * x * y ^ (p : ℤ) * x⁻¹ * y * x⁻¹ * y ^ (-p : ℤ) * x * y ^ (p : ℤ) * x⁻¹ * y ^ (-s : ℤ) * x * y ^ (-p : ℤ)) (y ^ (p : ℤ) * x⁻¹ * y ^ (s : ℤ) * x * y ^ (-p : ℤ) * x⁻¹)) :=
    conj0 _ _ (y ^ (p : ℤ) * x⁻¹ * y ^ (s : ℤ) * x * y ^ (-p : ℤ) * x⁻¹) _ (by group)
  have h10 : Steps (pair (x * x * y ^ (p : ℤ) * x⁻¹ * y * x⁻¹ * y ^ (-p : ℤ) * x * y ^ (p : ℤ) * x⁻¹ * y ^ (-s : ℤ) * x * y ^ (-p : ℤ)) (y ^ (p : ℤ) * x⁻¹ * y ^ (s : ℤ) * x * y ^ (-p : ℤ) * x⁻¹)) 1
      (pair (x * x * y ^ (p : ℤ) * x⁻¹ * y * x⁻¹ * y ^ (-p : ℤ)) (y ^ (p : ℤ) * x⁻¹ * y ^ (s : ℤ) * x * y ^ (-p : ℤ) * x⁻¹)) :=
    mul0 _ _ _ (by group)
  have h11 : Steps (pair (x * x * y ^ (p : ℤ) * x⁻¹ * y * x⁻¹ * y ^ (-p : ℤ)) (y ^ (p : ℤ) * x⁻¹ * y ^ (s : ℤ) * x * y ^ (-p : ℤ) * x⁻¹)) 1
      (pair (x * x * y ^ (p : ℤ) * x⁻¹ * y * x⁻¹ * y ^ (-p : ℤ)) (x * y ^ (p : ℤ) * x⁻¹ * y ^ (-s : ℤ) * x * y ^ (-p : ℤ))) :=
    inv1 _ _ _ (by group)
  have h12 : Steps (pair (x * x * y ^ (p : ℤ) * x⁻¹ * y * x⁻¹ * y ^ (-p : ℤ)) (x * y ^ (p : ℤ) * x⁻¹ * y ^ (-s : ℤ) * x * y ^ (-p : ℤ))) 1
      (pair (x * x * y ^ (p : ℤ) * x⁻¹ * y * x⁻¹ * y ^ (-p : ℤ)) (y ^ (p : ℤ) * x * y ^ (-s - 1 : ℤ) * x * y ^ (-p : ℤ) * x * y ^ (p : ℤ) * x⁻¹ * y * x⁻¹ * y ^ (-p : ℤ))) :=
    conj1 _ _ (y ^ (p : ℤ) * x * y⁻¹ * x * y ^ (-p : ℤ) * x⁻¹) _ (by group)
  have h13 : Steps (pair (x * x * y ^ (p : ℤ) * x⁻¹ * y * x⁻¹ * y ^ (-p : ℤ)) (y ^ (p : ℤ) * x * y ^ (-s - 1 : ℤ) * x * y ^ (-p : ℤ) * x * y ^ (p : ℤ) * x⁻¹ * y * x⁻¹ * y ^ (-p : ℤ))) 3
      (pair (x * y ^ (p : ℤ) * x⁻¹ * y ^ (s + 1 : ℤ) * x⁻¹ * y ^ (-p : ℤ)) (y ^ (p : ℤ) * x * y ^ (-s - 1 : ℤ) * x * y ^ (-p : ℤ) * x * y ^ (p : ℤ) * x⁻¹ * y * x⁻¹ * y ^ (-p : ℤ))) :=
    neg0 _ _ _ (by group)
  have h14 : Steps (pair (x * y ^ (p : ℤ) * x⁻¹ * y ^ (s + 1 : ℤ) * x⁻¹ * y ^ (-p : ℤ)) (y ^ (p : ℤ) * x * y ^ (-s - 1 : ℤ) * x * y ^ (-p : ℤ) * x * y ^ (p : ℤ) * x⁻¹ * y * x⁻¹ * y ^ (-p : ℤ))) 1
      (pair (x * y ^ (p : ℤ) * x⁻¹ * y ^ (s + 1 : ℤ) * x⁻¹ * y ^ (-p : ℤ)) (x * y ^ (p : ℤ) * x⁻¹ * y ^ (-s : ℤ) * x * y ^ (-p : ℤ))) :=
    conj1 _ _ (x * y ^ (p : ℤ) * x⁻¹ * y * x⁻¹ * y ^ (-p : ℤ)) _ (by group)
  have h15 : Steps (pair (x * y ^ (p : ℤ) * x⁻¹ * y ^ (s + 1 : ℤ) * x⁻¹ * y ^ (-p : ℤ)) (x * y ^ (p : ℤ) * x⁻¹ * y ^ (-s : ℤ) * x * y ^ (-p : ℤ))) 1
      (pair (y ^ (-p : ℤ) * x * y ^ (p : ℤ) * x⁻¹ * y ^ (s + 1 : ℤ) * x⁻¹) (x * y ^ (p : ℤ) * x⁻¹ * y ^ (-s : ℤ) * x * y ^ (-p : ℤ))) :=
    conj0 _ _ (y ^ (-p : ℤ)) _ (by group)
  have h16 : Steps (pair (y ^ (-p : ℤ) * x * y ^ (p : ℤ) * x⁻¹ * y ^ (s + 1 : ℤ) * x⁻¹) (x * y ^ (p : ℤ) * x⁻¹ * y ^ (-s : ℤ) * x * y ^ (-p : ℤ))) 1
      (pair (y ^ (-p : ℤ) * x * y ^ (p : ℤ) * x⁻¹ * y ^ (s + 1 : ℤ) * x⁻¹) (y ^ (-p : ℤ) * x * y ^ (-p : ℤ) * x * y ^ (p : ℤ) * x⁻¹ * y ^ (p - s : ℤ))) :=
    conj1 _ _ (y ^ (-p + s : ℤ) * x * y ^ (-p : ℤ) * x⁻¹) _ (by group)
  have h17 : Steps (pair (y ^ (-p : ℤ) * x * y ^ (p : ℤ) * x⁻¹ * y ^ (s + 1 : ℤ) * x⁻¹) (y ^ (-p : ℤ) * x * y ^ (-p : ℤ) * x * y ^ (p : ℤ) * x⁻¹ * y ^ (p - s : ℤ))) 1
      (pair (y ^ (-p : ℤ) * x * y ^ (p : ℤ) * x⁻¹ * y ^ (s + 1 : ℤ) * x⁻¹ * y ^ (-p : ℤ) * x * y ^ (-p : ℤ) * x * y ^ (p : ℤ) * x⁻¹ * y ^ (p - s : ℤ)) (y ^ (-p : ℤ) * x * y ^ (-p : ℤ) * x * y ^ (p : ℤ) * x⁻¹ * y ^ (p - s : ℤ))) :=
    mul0 _ _ _ (by group)
  have h18 : Steps (pair (y ^ (-p : ℤ) * x * y ^ (p : ℤ) * x⁻¹ * y ^ (s + 1 : ℤ) * x⁻¹ * y ^ (-p : ℤ) * x * y ^ (-p : ℤ) * x * y ^ (p : ℤ) * x⁻¹ * y ^ (p - s : ℤ)) (y ^ (-p : ℤ) * x * y ^ (-p : ℤ) * x * y ^ (p : ℤ) * x⁻¹ * y ^ (p - s : ℤ))) 1
      (pair (y ^ (-p + s : ℤ) * x * y ^ (-p : ℤ) * x⁻¹ * y ^ (p : ℤ) * x⁻¹ * y ^ (p : ℤ) * x * y ^ (-s - 1 : ℤ) * x * y ^ (-p : ℤ) * x⁻¹ * y ^ (p : ℤ)) (y ^ (-p : ℤ) * x * y ^ (-p : ℤ) * x * y ^ (p : ℤ) * x⁻¹ * y ^ (p - s : ℤ))) :=
    inv0 _ _ _ (by group)
  have h19 : Steps (pair (y ^ (-p + s : ℤ) * x * y ^ (-p : ℤ) * x⁻¹ * y ^ (p : ℤ) * x⁻¹ * y ^ (p : ℤ) * x * y ^ (-s - 1 : ℤ) * x * y ^ (-p : ℤ) * x⁻¹ * y ^ (p : ℤ)) (y ^ (-p : ℤ) * x * y ^ (-p : ℤ) * x * y ^ (p : ℤ) * x⁻¹ * y ^ (p - s : ℤ))) 1
      (pair (y ^ (-p + s : ℤ) * x * y ^ (-p : ℤ) * x⁻¹ * y ^ (p : ℤ) * x⁻¹ * y ^ (p : ℤ) * x * y ^ (-s - 1 : ℤ) * x * y ^ (-p : ℤ) * x⁻¹ * y ^ (p : ℤ)) (x * y ^ (-s - 1 : ℤ) * x * y ^ (-p : ℤ) * x⁻¹ * y ^ (p : ℤ))) :=
    mul1 _ _ _ (by group)
  have h20 : Steps (pair (y ^ (-p + s : ℤ) * x * y ^ (-p : ℤ) * x⁻¹ * y ^ (p : ℤ) * x⁻¹ * y ^ (p : ℤ) * x * y ^ (-s - 1 : ℤ) * x * y ^ (-p : ℤ) * x⁻¹ * y ^ (p : ℤ)) (x * y ^ (-s - 1 : ℤ) * x * y ^ (-p : ℤ) * x⁻¹ * y ^ (p : ℤ))) 1
      (pair (y ^ (-p : ℤ) * x * y ^ (p : ℤ) * x⁻¹ * y ^ (s + 1 : ℤ) * x⁻¹ * y ^ (-p : ℤ) * x * y ^ (-p : ℤ) * x * y ^ (p : ℤ) * x⁻¹ * y ^ (p - s : ℤ)) (x * y ^ (-s - 1 : ℤ) * x * y ^ (-p : ℤ) * x⁻¹ * y ^ (p : ℤ))) :=
    inv0 _ _ _ (by group)
  have h21 : Steps (pair (y ^ (-p : ℤ) * x * y ^ (p : ℤ) * x⁻¹ * y ^ (s + 1 : ℤ) * x⁻¹ * y ^ (-p : ℤ) * x * y ^ (-p : ℤ) * x * y ^ (p : ℤ) * x⁻¹ * y ^ (p - s : ℤ)) (x * y ^ (-s - 1 : ℤ) * x * y ^ (-p : ℤ) * x⁻¹ * y ^ (p : ℤ))) 1
      (pair (y ^ (-p : ℤ) * x * y ^ (-p : ℤ) * x * y ^ (p : ℤ) * x⁻¹ * y ^ (-s : ℤ) * x * y ^ (p : ℤ) * x⁻¹ * y ^ (s + 1 : ℤ) * x⁻¹) (x * y ^ (-s - 1 : ℤ) * x * y ^ (-p : ℤ) * x⁻¹ * y ^ (p : ℤ))) :=
    conj0 _ _ (x * y ^ (-s - 1 : ℤ) * x * y ^ (-p : ℤ) * x⁻¹ * y ^ (p : ℤ)) _ (by group)
  have h22 : Steps (pair (y ^ (-p : ℤ) * x * y ^ (-p : ℤ) * x * y ^ (p : ℤ) * x⁻¹ * y ^ (-s : ℤ) * x * y ^ (p : ℤ) * x⁻¹ * y ^ (s + 1 : ℤ) * x⁻¹) (x * y ^ (-s - 1 : ℤ) * x * y ^ (-p : ℤ) * x⁻¹ * y ^ (p : ℤ))) 1
      (pair (y ^ (-p : ℤ) * x * y ^ (-p : ℤ) * x * y ^ (p : ℤ) * x⁻¹ * y ^ (p - s : ℤ)) (x * y ^ (-s - 1 : ℤ) * x * y ^ (-p : ℤ) * x⁻¹ * y ^ (p : ℤ))) :=
    mul0 _ _ _ (by group)
  have h23 : Steps (pair (y ^ (-p : ℤ) * x * y ^ (-p : ℤ) * x * y ^ (p : ℤ) * x⁻¹ * y ^ (p - s : ℤ)) (x * y ^ (-s - 1 : ℤ) * x * y ^ (-p : ℤ) * x⁻¹ * y ^ (p : ℤ))) 1
      (pair (y ^ (-p : ℤ) * x * y ^ (-p : ℤ) * x * y ^ (p : ℤ) * x⁻¹ * y ^ (p - s : ℤ)) (y ^ (-p : ℤ) * x * y ^ (p : ℤ) * x⁻¹ * y ^ (s + 1 : ℤ) * x⁻¹)) :=
    inv1 _ _ _ (by group)
  have h24 : Steps (pair (y ^ (-p : ℤ) * x * y ^ (-p : ℤ) * x * y ^ (p : ℤ) * x⁻¹ * y ^ (p - s : ℤ)) (y ^ (-p : ℤ) * x * y ^ (p : ℤ) * x⁻¹ * y ^ (s + 1 : ℤ) * x⁻¹)) 1
      (pair (y ^ (-p : ℤ) * x * y ^ (-p : ℤ) * x * y ^ (p : ℤ) * x⁻¹ * y ^ (p - s : ℤ)) (y ^ (-p + 2 * s + 1 : ℤ) * x⁻¹ * y ^ (-p : ℤ) * x * y ^ (p : ℤ) * x⁻¹ * y ^ (p - s : ℤ))) :=
    conj1 _ _ (y ^ (-p + s : ℤ) * x * y ^ (-p : ℤ) * x⁻¹ * y ^ (p : ℤ)) _ (by group)
  have h25 : Steps (pair (y ^ (-p : ℤ) * x * y ^ (-p : ℤ) * x * y ^ (p : ℤ) * x⁻¹ * y ^ (p - s : ℤ)) (y ^ (-p + 2 * s + 1 : ℤ) * x⁻¹ * y ^ (-p : ℤ) * x * y ^ (p : ℤ) * x⁻¹ * y ^ (p - s : ℤ))) 3
      (pair (y ^ (-p : ℤ) * x * x * y ^ (p - 2 * s - 1 : ℤ)) (y ^ (-p + 2 * s + 1 : ℤ) * x⁻¹ * y ^ (-p : ℤ) * x * y ^ (p : ℤ) * x⁻¹ * y ^ (p - s : ℤ))) :=
    neg0 _ _ _ (by group)
  have h26 : Steps (pair (y ^ (-p : ℤ) * x * x * y ^ (p - 2 * s - 1 : ℤ)) (y ^ (-p + 2 * s + 1 : ℤ) * x⁻¹ * y ^ (-p : ℤ) * x * y ^ (p : ℤ) * x⁻¹ * y ^ (p - s : ℤ))) 1
      (pair (y ^ (-p : ℤ) * x * x * y ^ (p - 2 * s - 1 : ℤ)) (y ^ (-p : ℤ) * x * y ^ (p : ℤ) * x⁻¹ * y ^ (s + 1 : ℤ) * x⁻¹)) :=
    conj1 _ _ (y ^ (-p : ℤ) * x * y ^ (p : ℤ) * x⁻¹ * y ^ (p - s : ℤ)) _ (by group)
  have h27 : Steps (pair (y ^ (-p : ℤ) * x * x * y ^ (p - 2 * s - 1 : ℤ)) (y ^ (-p : ℤ) * x * y ^ (p : ℤ) * x⁻¹ * y ^ (s + 1 : ℤ) * x⁻¹)) 1
      (pair (y ^ (-p + 2 * s + 1 : ℤ) * x⁻¹ * x⁻¹ * y ^ (p : ℤ)) (y ^ (-p : ℤ) * x * y ^ (p : ℤ) * x⁻¹ * y ^ (s + 1 : ℤ) * x⁻¹)) :=
    inv0 _ _ _ (by group)
  have h28 : Steps (pair (y ^ (-p + 2 * s + 1 : ℤ) * x⁻¹ * x⁻¹ * y ^ (p : ℤ)) (y ^ (-p : ℤ) * x * y ^ (p : ℤ) * x⁻¹ * y ^ (s + 1 : ℤ) * x⁻¹)) 1
      (pair (y ^ (-p + s + 1 : ℤ) * x⁻¹ * x⁻¹ * y ^ (p + s : ℤ)) (y ^ (-p : ℤ) * x * y ^ (p : ℤ) * x⁻¹ * y ^ (s + 1 : ℤ) * x⁻¹)) :=
    conj0 _ _ (y ^ (-s : ℤ)) _ (by group)
  have h29 : Steps (pair (y ^ (-p + s + 1 : ℤ) * x⁻¹ * x⁻¹ * y ^ (p + s : ℤ)) (y ^ (-p : ℤ) * x * y ^ (p : ℤ) * x⁻¹ * y ^ (s + 1 : ℤ) * x⁻¹)) 1
      (pair (y ^ (-p + s + 1 : ℤ) * x⁻¹ * x⁻¹ * y ^ (p + s : ℤ)) (y ^ (-p + s + 1 : ℤ) * x⁻¹ * y ^ (s + 1 : ℤ) * x⁻¹ * y ^ (-p : ℤ) * x * y ^ (2 * p - s - 1 : ℤ))) :=
    conj1 _ _ (y ^ (-2 * p + s + 1 : ℤ) * x⁻¹ * y ^ (p : ℤ)) _ (by group)
  have h30 : Steps (pair (y ^ (-p + s + 1 : ℤ) * x⁻¹ * x⁻¹ * y ^ (p + s : ℤ)) (y ^ (-p + s + 1 : ℤ) * x⁻¹ * y ^ (s + 1 : ℤ) * x⁻¹ * y ^ (-p : ℤ) * x * y ^ (2 * p - s - 1 : ℤ))) 1
      (pair (y ^ (-p + s + 1 : ℤ) * x⁻¹ * x⁻¹ * y ^ (2 * s + 1 : ℤ) * x⁻¹ * y ^ (s + 1 : ℤ) * x⁻¹ * y ^ (-p : ℤ) * x * y ^ (2 * p - s - 1 : ℤ)) (y ^ (-p + s + 1 : ℤ) * x⁻¹ * y ^ (s + 1 : ℤ) * x⁻¹ * y ^ (-p : ℤ) * x * y ^ (2 * p - s - 1 : ℤ))) :=
    mul0 _ _ _ (by group)
  have h31 : Steps (pair (y ^ (-p + s + 1 : ℤ) * x⁻¹ * x⁻¹ * y ^ (2 * s + 1 : ℤ) * x⁻¹ * y ^ (s + 1 : ℤ) * x⁻¹ * y ^ (-p : ℤ) * x * y ^ (2 * p - s - 1 : ℤ)) (y ^ (-p + s + 1 : ℤ) * x⁻¹ * y ^ (s + 1 : ℤ) * x⁻¹ * y ^ (-p : ℤ) * x * y ^ (2 * p - s - 1 : ℤ))) 1
      (pair (y ^ (-2 * p + s + 1 : ℤ) * x⁻¹ * y ^ (p : ℤ) * x * y ^ (-s - 1 : ℤ) * x * y ^ (-2 * s - 1 : ℤ) * x * x * y ^ (p - s - 1 : ℤ)) (y ^ (-p + s + 1 : ℤ) * x⁻¹ * y ^ (s + 1 : ℤ) * x⁻¹ * y ^ (-p : ℤ) * x * y ^ (2 * p - s - 1 : ℤ))) :=
    inv0 _ _ _ (by group; simp only [zpow_ofNat, pow_two, mul_assoc])
  have h32 : Steps (pair (y ^ (-2 * p + s + 1 : ℤ) * x⁻¹ * y ^ (p : ℤ) * x * y ^ (-s - 1 : ℤ) * x * y ^ (-2 * s - 1 : ℤ) * x * x * y ^ (p - s - 1 : ℤ)) (y ^ (-p + s + 1 : ℤ) * x⁻¹ * y ^ (s + 1 : ℤ) * x⁻¹ * y ^ (-p : ℤ) * x * y ^ (2 * p - s - 1 : ℤ))) 1
      (pair (y ^ (-2 * p + s + 1 : ℤ) * x⁻¹ * y ^ (p : ℤ) * x * y ^ (-s - 1 : ℤ) * x * y ^ (-2 * s - 1 : ℤ) * x * x * y ^ (p - s - 1 : ℤ)) (y ^ (-p - s : ℤ) * x * x * y ^ (p - s - 1 : ℤ))) :=
    mul1 _ _ _ (by group)
  have h33 : Steps (pair (y ^ (-2 * p + s + 1 : ℤ) * x⁻¹ * y ^ (p : ℤ) * x * y ^ (-s - 1 : ℤ) * x * y ^ (-2 * s - 1 : ℤ) * x * x * y ^ (p - s - 1 : ℤ)) (y ^ (-p - s : ℤ) * x * x * y ^ (p - s - 1 : ℤ))) 1
      (pair (y ^ (-p + s + 1 : ℤ) * x⁻¹ * x⁻¹ * y ^ (2 * s + 1 : ℤ) * x⁻¹ * y ^ (s + 1 : ℤ) * x⁻¹ * y ^ (-p : ℤ) * x * y ^ (2 * p - s - 1 : ℤ)) (y ^ (-p - s : ℤ) * x * x * y ^ (p - s - 1 : ℤ))) :=
    inv0 _ _ _ (by group)
  have h34 : Steps (pair (y ^ (-p + s + 1 : ℤ) * x⁻¹ * x⁻¹ * y ^ (2 * s + 1 : ℤ) * x⁻¹ * y ^ (s + 1 : ℤ) * x⁻¹ * y ^ (-p : ℤ) * x * y ^ (2 * p - s - 1 : ℤ)) (y ^ (-p - s : ℤ) * x * x * y ^ (p - s - 1 : ℤ))) 1
      (pair (y ^ (-p + s + 1 : ℤ) * x⁻¹ * y ^ (s + 1 : ℤ) * x⁻¹ * y ^ (-p : ℤ) * x * y ^ (p : ℤ) * x⁻¹ * x⁻¹ * y ^ (p + s : ℤ)) (y ^ (-p - s : ℤ) * x * x * y ^ (p - s - 1 : ℤ))) :=
    conj0 _ _ (y ^ (-p - s : ℤ) * x * x * y ^ (p - s - 1 : ℤ)) _ (by group)
  have h35 : Steps (pair (y ^ (-p + s + 1 : ℤ) * x⁻¹ * y ^ (s + 1 : ℤ) * x⁻¹ * y ^ (-p : ℤ) * x * y ^ (p : ℤ) * x⁻¹ * x⁻¹ * y ^ (p + s : ℤ)) (y ^ (-p - s : ℤ) * x * x * y ^ (p - s - 1 : ℤ))) 1
      (pair (y ^ (-p + s + 1 : ℤ) * x⁻¹ * y ^ (s + 1 : ℤ) * x⁻¹ * y ^ (-p : ℤ) * x * y ^ (2 * p - s - 1 : ℤ)) (y ^ (-p - s : ℤ) * x * x * y ^ (p - s - 1 : ℤ))) :=
    mul0 _ _ _ (by group)
  have h36 : Steps (pair (y ^ (-p + s + 1 : ℤ) * x⁻¹ * y ^ (s + 1 : ℤ) * x⁻¹ * y ^ (-p : ℤ) * x * y ^ (2 * p - s - 1 : ℤ)) (y ^ (-p - s : ℤ) * x * x * y ^ (p - s - 1 : ℤ))) 1
      (pair (y ^ (-p + s + 1 : ℤ) * x⁻¹ * y ^ (s + 1 : ℤ) * x⁻¹ * y ^ (-p : ℤ) * x * y ^ (2 * p - s - 1 : ℤ)) (y ^ (-p + s + 1 : ℤ) * x⁻¹ * x⁻¹ * y ^ (p + s : ℤ))) :=
    inv1 _ _ _ (by group)
  have h37 : Steps (pair (y ^ (-p + s + 1 : ℤ) * x⁻¹ * y ^ (s + 1 : ℤ) * x⁻¹ * y ^ (-p : ℤ) * x * y ^ (2 * p - s - 1 : ℤ)) (y ^ (-p + s + 1 : ℤ) * x⁻¹ * x⁻¹ * y ^ (p + s : ℤ))) 1
      (pair (y ^ (-p + s + 1 : ℤ) * x⁻¹ * y ^ (s + 1 : ℤ) * x⁻¹ * y ^ (-p : ℤ) * x * y ^ (2 * p - s - 1 : ℤ)) (y ^ (-p + s + 1 : ℤ) * x⁻¹ * y ^ (2 * s + 1 : ℤ) * x⁻¹ * y ^ (p - s - 1 : ℤ))) :=
    conj1 _ _ (y ^ (-p + s + 1 : ℤ) * x⁻¹ * y ^ (p + s : ℤ)) _ (by group)
  have h38 : Steps (pair (y ^ (-p + s + 1 : ℤ) * x⁻¹ * y ^ (s + 1 : ℤ) * x⁻¹ * y ^ (-p : ℤ) * x * y ^ (2 * p - s - 1 : ℤ)) (y ^ (-p + s + 1 : ℤ) * x⁻¹ * y ^ (2 * s + 1 : ℤ) * x⁻¹ * y ^ (p - s - 1 : ℤ))) 1
      (pair (y ^ (-p + s + 1 : ℤ) * x⁻¹ * y ^ (s + 1 : ℤ) * x⁻¹ * y ^ (-p : ℤ) * x * y ^ (2 * p - s - 1 : ℤ)) (y ^ (-p + s + 1 : ℤ) * x * y ^ (-2 * s - 1 : ℤ) * x * y ^ (p - s - 1 : ℤ))) :=
    inv1 _ _ _ (by group)
  have h39 : Steps (pair (y ^ (-p + s + 1 : ℤ) * x⁻¹ * y ^ (s + 1 : ℤ) * x⁻¹ * y ^ (-p : ℤ) * x * y ^ (2 * p - s - 1 : ℤ)) (y ^ (-p + s + 1 : ℤ) * x * y ^ (-2 * s - 1 : ℤ) * x * y ^ (p - s - 1 : ℤ))) 1
      (pair (y ^ (s + 1 : ℤ) * x⁻¹ * y ^ (s + 1 : ℤ) * x⁻¹ * y ^ (-p : ℤ) * x * y ^ (p - s - 1 : ℤ)) (y ^ (-p + s + 1 : ℤ) * x * y ^ (-2 * s - 1 : ℤ) * x * y ^ (p - s - 1 : ℤ))) :=
    conj0 _ _ (y ^ (p : ℤ)) _ (by group)
  have he : applyHom (entryMap p s) (pair (root p) (companion s)) = pair (y ^ (s + 1 : ℤ) * x⁻¹ * y ^ (s + 1 : ℤ) * x⁻¹ * y ^ (-p : ℤ) * x * y ^ (p - s - 1 : ℤ)) (y ^ (-p + s + 1 : ℤ) * x * y ^ (-2 * s - 1 : ℤ) * x * y ^ (p - s - 1 : ℤ)) := by
    ext i
    fin_cases i <;> simp [applyHom, pair, root, companion, map_mul, map_inv, map_zpow, pow_two] <;> group
  rw [hi, he]
  exact ((((((((((((((((((((((((((((((((((((((h1.trans h2).trans h3).trans h4).trans h5).trans h6).trans h7).trans h8).trans h9).trans h10).trans h11).trans h12).trans h13).trans h14).trans h15).trans h16).trans h17).trans h18).trans h19).trans h20).trans h21).trans h22).trans h23).trans h24).trans h25).trans h26).trans h27).trans h28).trans h29).trans h30).trans h31).trans h32).trans h33).trans h34).trans h35).trans h36).trans h37).trans h38).trans h39)

/-- The image basis is solved by charged ordinary moves. -/
theorem entryMap_standard (p s : ℤ) :
    Reachable (applyHom (entryMap p s) (standard 2)) (standard 2) := by
  let r : Word 2 := y ^ (s + 1 - p) * x⁻¹ * y ^ p
  have hi : applyHom (entryMap p s) (standard 2) = pair r y⁻¹ := by
    ext i
    fin_cases i <;> simp [applyHom, standard, entryMap, pair, r, x, y]
  have h₁ : Steps (pair r y⁻¹) 1 (pair (x⁻¹ * y ^ (s + 1)) y⁻¹) :=
    conj0 _ _ (y ^ (p - s - 1)) _ (by dsimp [r]; group)
  have h₂ : Reachable (pair (x⁻¹ * y ^ (s + 1)) y⁻¹) (pair x⁻¹ y⁻¹) := by
    have h := (mulRight_zpow (pair (x⁻¹ * y ^ (s + 1)) y⁻¹) 0 1 (by decide) (s + 1)).reachable
    have he : (x⁻¹ * y ^ (s + 1)) * (y⁻¹) ^ (s + 1) = x⁻¹ := by group
    simpa only [pair_zero, pair_one, pair_update_zero, he] using h
  have h₃ := (inv0 x⁻¹ y⁻¹ x (by group)).reachable
  have h₄ := (inv1 x y⁻¹ y (by group)).reachable
  have he : pair x y = standard 2 := by ext i; fin_cases i <;> rfl
  rw [hi]
  simpa only [he] using h₁.reachable.trans (h₂.trans (h₃.trans h₄))

/-- The entire square-family problem reduces to the root-conjugacy family.
The image basis is explicitly restored, so generator changes are not free moves. -/
theorem square_of_root (p s : ℤ)
    (h : Reachable (pair (root p) (companion s)) (standard 2)) :
    Reachable (Diagonal.generalSquare p s) (standard 2) :=
  (Diagonal.general_normal_form p s).reachable.trans ((root_entry p s).reachable.trans
    (solvable_hom (entryMap p s) _ h (entryMap_standard p s)))

/-- The entire p=2 positive-sign square slice is ordinarily AC-solvable. -/
theorem square_p2_solvable (s : ℕ) :
    Reachable (Diagonal.generalSquare 2 s) (standard 2) :=
  (Diagonal.general_normal_form 2 s).reachable.trans ((root_entry 2 s).reachable.trans
    (solvable_hom (entryMap 2 s) _ (root_solvable s) (entryMap_standard 2 s)))

end AC.MillerSchupp.SquareFamily.P2
